### ISSUE TITLE
Change in getIISSInfo

### ISSUE THREAD

**Issue by robcxyz** [icon-project/governance#38]
The method getIISSInfo seems to have recently changed and has now broken three cards in the governance P-Rep list view on the the tracker (https://tracker.icon.foundation/governance) - Global commission rate, i-rep, and reward rate.  getIISSInfo now returns:

```
Icps: "0xa" (11) - ?
Iglobal: "0x27b46536c66c8e3000000" (3e24) - Not sure what this represents 
Iprep: "0xd" (13) - Should have been a larger number that a percentage could be derived
Irelay: "0x0" (0)  - ?
Ivoter: "0x4d" (77) - ?
```

For global commision rate it was calculated as:
`const glbComRate = ((1 / totalVoted * 100 * 12 * irep / 2) / ((rrep * 3 / 10000) + 1 / totalVoted * 100 * 12 * irep / 2)) * 100;`

We have totalVoted but with the change in getIISSInfo we are now missing irep and rrep. 

How do we get irep and rrep now?

**Comment by eunsoo-icon** [comment]
I-rep and R-rep were used in IISS 2.0

ICON mainnet works with IISS 3.1 since Revision 14.

You can find out the meaning of Iglobal, Iprep, Icps, Irealay and Ivoter in this [link](https://forum.icon.community/t/iiss-3-1-structure/1309).

**Comment by robcxyz** [comment]
Thanks @eunsoo-icon for getting back to me. 

Just want to clarify that from the link you sent me, `As a rule, i_prep + i_voter + i_relay + i_cpf + i_n must always equal 100%.` 

When looking at the numbers, disregarding Iglobal we have 77+11+13=101.  Can you let me know why this is the case?  Also can you confirm these numbers will always be integers and never floats?

**Comment by eunsoo-icon** [comment]
Main P-Reps can set  Iprep, Icps, Irelay and Ivoter by `Reward Fund Allocaltion Proposal`. [mainnet proposal](https://tracker.icon.foundation/proposal/0x2d82b7c7ac882d63c3fc7c31df30262f9033e34edc52b4f22758de66131dce39)

Each value must be an integer and the sum must be 100. (0xa == 10)

**Comment by robcxyz** [comment]
@eunsoo-icon - Ah my bad.  Wrong conversion.  Makes sense thank you.
